// examples-svelte/demo/src/App.svelte
<script lang="ts">
  import BasicFlow from "./flows/BasicFlow.svelte";
  import GroupsFlow from "./flows/GroupsFlow.svelte";
  import SubflowsFlow from "./flows/SubflowsFlow.svelte";
  import AutoLayoutFlow from "./flows/AutoLayoutFlow.svelte";
  import AutoLayoutGroupsFlow from "./flows/AutoLayoutGroupsFlow.svelte";
  import StressTestFlow from "./flows/StressTestFlow.svelte";
  import DAGFlow from "./flows/DAGFlow.svelte";
  import TreeFlow from "./flows/TreeFlow.svelte";

  type Tab = "basic" | "group" | "subflows" | "dag" | "tree" | "elk" | "auto-layout-groups" | "stress";

  const validTabs: Tab[] = ["basic", "group", "subflows", "dag", "tree", "elk", "auto-layout-groups", "stress"];

  function getInitialTab(): Tab {
    const params = new URLSearchParams(window.location.search);
    const example = params.get("example") as Tab | null;
    return example && validTabs.includes(example) ? example : "basic";
  }

  let tab: Tab = getInitialTab();

  function setTab(newTab: Tab) {
    tab = newTab;
    const url = new URL(window.location.href);
    url.searchParams.set("example", newTab);
    window.history.replaceState({}, "", url.toString());
  }

  const tabs: { id: Tab; label: string }[] = [
    { id: "basic", label: "Basic" },
    { id: "group", label: "Groups" },
    { id: "subflows", label: "Subflows" },
    { id: "dag", label: "Complex DAG" },
    { id: "tree", label: "Tree (Circles)" },
    { id: "elk", label: "Auto Layout" },
    { id: "auto-layout-groups", label: "Auto Layout + Groups" },
    { id: "stress", label: "Stress Test (200)" },
  ];
</script>

<div class="flow-container">
  {#key tab}
    {#if tab === "basic"}
      <BasicFlow />
    {:else if tab === "group"}
      <GroupsFlow />
    {:else if tab === "subflows"}
      <SubflowsFlow />
    {:else if tab === "dag"}
      <DAGFlow />
    {:else if tab === "tree"}
      <TreeFlow />
    {:else if tab === "elk"}
      <AutoLayoutFlow />
    {:else if tab === "auto-layout-groups"}
      <AutoLayoutGroupsFlow />
    {:else if tab === "stress"}
      <StressTestFlow />
    {/if}
  {/key}

  <div class="tab-bar">
    {#each tabs as t}
      <button
        class="tab-btn"
        class:active={tab === t.id}
        on:click={() => setTab(t.id)}
      >
        {t.label}
      </button>
    {/each}
  </div>
</div>

<style>
  :global(html, body, #app) {
    width: 100%;
    height: 100%;
    margin: 0;
    padding: 0;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  }

  :global(.svelte-flow) {
    --xy-background-color: #f7f9fb;
    --xy-theme-selected: #f57dbd;
    --xy-theme-hover: #c5c5c5;
    --xy-theme-edge-hover: black;
    --xy-theme-color-focus: #e8e8e8;
    --xy-node-border-default: 1px solid #ededed;
    --xy-node-boxshadow-default:
      0px 3.54px 4.55px 0px #00000005, 0px 3.54px 4.55px 0px #0000000d,
      0px 0.51px 1.01px 0px #0000001a;
    --xy-node-border-radius-default: 8px;
    --xy-handle-background-color-default: #ffffff;
    --xy-handle-border-color-default: #aaaaaa;
    --xy-edge-label-color-default: #505050;
  }

  :global(.svelte-flow__node) {
    box-shadow: var(--xy-node-boxshadow-default);
    border-radius: var(--xy-node-border-radius-default);
    display: flex;
    justify-content: center;
    align-items: center;
    text-align: center;
    padding: 10px;
    font-size: 12px;
    flex-direction: column;
    border: var(--xy-node-border-default);
  }

  :global(.svelte-flow__node.selectable:hover),
  :global(.svelte-flow__node.draggable:hover) {
    border-color: var(--xy-theme-hover);
  }

  :global(.svelte-flow__node.selectable.selected) {
    border-color: var(--xy-theme-selected);
  }

  :global(.svelte-flow__node-group) {
    background-color: rgba(207, 182, 255, 0.4);
    border-color: #9e86ed;
  }

  :global(.svelte-flow__handle) {
    visibility: hidden;
  }

  .flow-container {
    width: 100vw;
    height: 100vh;
    position: relative;
  }

  .tab-bar {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    display: flex;
    align-items: center;
    gap: 4px;
    z-index: 20;
    padding: 8px 12px;
    overflow-x: auto;
    background: rgba(255, 255, 255, 0.85);
    backdrop-filter: blur(8px);
    border-bottom: 1px solid #e5e5e5;
    white-space: nowrap;
    scrollbar-width: thin;
    scrollbar-color: #888 #e5e5e5;
  }

  .tab-bar::-webkit-scrollbar {
    height: 6px;
    display: block !important;
  }

  .tab-bar::-webkit-scrollbar-track {
    background: #e5e5e5;
  }

  .tab-bar::-webkit-scrollbar-thumb {
    background: #888;
    border-radius: 6px;
  }

  .tab-bar::-webkit-scrollbar-thumb:hover {
    background: #555;
  }

  .tab-btn {
    padding: 6px 16px;
    border-radius: 6px;
    border: 1px solid #ccc;
    background: #fff;
    color: #333;
    cursor: pointer;
    font-size: 13px;
    font-weight: 400;
    flex-shrink: 0;
  }

  .tab-btn.active {
    background: #333;
    color: #fff;
    font-weight: 600;
  }
</style>

// examples-server-side/express-api-example/src/App.tsx
import { useCallback, useEffect, useState } from "react";
import {
  ReactFlow,
  Background,
  Controls,
  type Node,
  type Edge,
} from "@xyflow/react";
import "@xyflow/react/dist/style.css";

import { ServerRoutedEdge, RoutesContext } from "./ServerRoutedEdge";
import { GroupNode } from "./GroupNode";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const edgeTypes = { avoidNodes: ServerRoutedEdge } as any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const nodeTypes = { group: GroupNode } as any;

type AvoidRoute = { path: string; labelX: number; labelY: number };

type TabName = "basic" | "group" | "subflows" | "dag" | "tree" | "elk" | "auto-layout-groups" | "stress";

const tabs: { key: TabName; label: string }[] = [
  { key: "basic", label: "Basic" },
  { key: "group", label: "Groups" },
  { key: "subflows", label: "Subflows" },
  { key: "dag", label: "Complex DAG" },
  { key: "tree", label: "Tree (Circles)" },
  { key: "elk", label: "Auto Layout" },
  { key: "auto-layout-groups", label: "Auto Layout + Groups" },
  { key: "stress", label: "Stress Test (200)" },
];

const API_BASE = "http://localhost:3004";

export default function App() {
  const [activeTab, setActiveTab] = useState<TabName>(() => {
    const params = new URLSearchParams(window.location.search);
    return (params.get("tab") as TabName) || "basic";
  });
  const [nodes, setNodes] = useState<Node[]>([]);
  const [edges, setEdges] = useState<Edge[]>([]);
  const [routes, setRoutes] = useState<Record<string, AvoidRoute>>({});
  const [loading, setLoading] = useState(true);

  const fetchDiagram = useCallback((tab: TabName) => {
    setLoading(true);
    fetch(`${API_BASE}/api/diagram?tab=${tab}`)
      .then((res) => res.json())
      .then((data) => {
        setNodes(data.nodes);
        setEdges(data.edges);
        setRoutes(data.routes);
        setLoading(false);
      })
      .catch((err) => {
        console.error("Failed to fetch diagram:", err);
        setLoading(false);
      });
  }, []);

  useEffect(() => {
    fetchDiagram(activeTab);
  }, [activeTab, fetchDiagram]);

  const handleTabClick = (tab: TabName) => {
    setActiveTab(tab);
    const url = new URL(window.location.href);
    url.searchParams.set("tab", tab);
    window.history.replaceState({}, "", url.toString());
  };

  return (
    <div style={{ width: "100vw", height: "100vh", display: "flex", flexDirection: "column" }}>
      {/* Tab bar */}
      <div
        style={{
          display: "flex",
          gap: 4,
          padding: "8px 12px",
          background: "#f8fafc",
          borderBottom: "1px solid #e2e8f0",
          overflowX: "auto",
          flexShrink: 0,
        }}
      >
        {tabs.map(({ key, label }) => (
          <button
            key={key}
            onClick={() => handleTabClick(key)}
            style={{
              padding: "6px 14px",
              borderRadius: 6,
              border: activeTab === key ? "1px solid #818cf8" : "1px solid #e2e8f0",
              background: activeTab === key ? "#818cf8" : "#fff",
              color: activeTab === key ? "#fff" : "#334155",
              cursor: "pointer",
              fontSize: 13,
              fontWeight: activeTab === key ? 600 : 400,
              whiteSpace: "nowrap",
              transition: "all 0.15s",
            }}
          >
            {label}
          </button>
        ))}
        <div
          style={{
            marginLeft: "auto",
            fontSize: 11,
            color: "#94a3b8",
            display: "flex",
            alignItems: "center",
            whiteSpace: "nowrap",
          }}
        >
          Server-Side: ELK layout + edge routing
        </div>
      </div>

      {/* Flow area */}
      <div style={{ flex: 1, position: "relative" }}>
        {loading && (
          <div
            style={{
              position: "absolute",
              inset: 0,
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              zIndex: 20,
              background: "rgba(255,255,255,0.8)",
              fontSize: 14,
              color: "#64748b",
            }}
          >
            Loading diagram from server...
          </div>
        )}
        <RoutesContext.Provider value={routes}>
          <ReactFlow
            key={activeTab}
            nodes={nodes}
            edges={edges}
            edgeTypes={edgeTypes}
            nodeTypes={nodeTypes}
            fitView
            nodesDraggable={false}
          >
            <Background />
            <Controls />
          </ReactFlow>
        </RoutesContext.Provider>
      </div>
    </div>
  );
}
