// examples/remote-basic/src/App.tsx
import { useState, useCallback } from 'react';
import {
  ReactFlow,
  ReactFlowProvider,
  applyNodeChanges,
  applyEdgeChanges,
  addEdge,
  type Node,
  type Edge,
  type NodeChange,
  type EdgeChange,
  type Connection,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';

import { useAvoidNodesRouterFromWorker } from 'avoid-nodes-edge';
import { AvoidNodesEdge } from 'avoid-nodes-edge/edge';

const edgeTypes = { avoidNodes: AvoidNodesEdge };

const initialNodes: Node[] = [
  { id: '1', position: { x: 0, y: 0 }, data: { label: 'Node 1' } },
  { id: '2', position: { x: 400, y: 0 }, data: { label: 'Node 2' } },
  { id: '3', position: { x: 200, y: 0 }, data: { label: 'Blocker' } },
  { id: '4', position: { x: 200, y: 200 }, data: { label: 'Node 4' } },
];

const initialEdges: Edge[] = [
  { id: 'e1-2', source: '1', target: '2', type: 'avoidNodes' },
  { id: 'e1-4', source: '1', target: '4', type: 'avoidNodes' },
];

function Flow() {
  const [nodes, setNodes] = useState<Node[]>(initialNodes);
  const [edges, setEdges] = useState<Edge[]>(initialEdges);

  const { updateRoutingOnNodesChange, resetRouting } =
    useAvoidNodesRouterFromWorker(nodes, edges, {
      edgeToNodeSpacing: 12,
      edgeToEdgeSpacing: 10,
      edgeRounding: 8,
    });

  const onNodesChange = useCallback(
    (changes: NodeChange<Node>[]) => {
      setNodes((nds) => applyNodeChanges(changes, nds));
      updateRoutingOnNodesChange(changes);
    },
    [updateRoutingOnNodesChange]
  );

  const onEdgesChange = useCallback(
    (changes: EdgeChange<Edge>[]) => {
      setEdges((eds) => applyEdgeChanges(changes, eds));
      if (changes.some((c) => c.type === 'add' || c.type === 'remove')) {
        requestAnimationFrame(() => resetRouting());
      }
    },
    [resetRouting]
  );

  const onConnect = useCallback(
    (params: Connection) => {
      setEdges((eds) => addEdge({ ...params, type: 'avoidNodes' }, eds));
      requestAnimationFrame(() => resetRouting());
    },
    [resetRouting]
  );

  return (
    <div style={{ width: '100vw', height: '100vh' }}>
      <ReactFlow
        nodes={nodes}
        edges={edges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        edgeTypes={edgeTypes}
        defaultEdgeOptions={{ type: 'avoidNodes' }}
        fitView
      />
    </div>
  );
}

export default function App() {
  return (
    <ReactFlowProvider>
      <Flow />
    </ReactFlowProvider>
  );
}

// examples-svelte/basic/src/App.svelte
<script lang="ts">
  import { writable } from "svelte/store";
  import {
    SvelteFlow,
    Background,
    Controls,
    MiniMap,
    type Node,
    type Edge,
    type EdgeTypes,
  } from "@xyflow/svelte";
  import "@xyflow/svelte/dist/style.css";

  import AvoidNodesEdge from "avoid-nodes-edge-svelte/edge";
  import {
    createAvoidNodesRouter,
    resolveCollisions,
  } from "avoid-nodes-edge-svelte";

  const edgeTypes: EdgeTypes = {
    avoidNodes: AvoidNodesEdge as any,
  };

  const initialNodes: Node[] = [
    {
      id: "source",
      type: "default",
      position: { x: 0, y: 100 },
      data: { label: "Source" },
      style: "width: 150px; height: 50px;",
    },
    {
      id: "blocker-1",
      type: "default",
      position: { x: 250, y: 50 },
      data: { label: "Blocker 1" },
      style: "width: 150px; height: 50px;",
    },
    {
      id: "blocker-2",
      type: "default",
      position: { x: 250, y: 200 },
      data: { label: "Blocker 2" },
      style: "width: 150px; height: 50px;",
    },
    {
      id: "target",
      type: "default",
      position: { x: 500, y: 100 },
      data: { label: "Target" },
      style: "width: 150px; height: 50px;",
    },
  ];

  const initialEdges: Edge[] = [
    {
      id: "e-source-target",
      source: "source",
      target: "target",
      type: "avoidNodes",
      data: { label: "routed edge" },
    },
  ];

  const nodes = writable<Node[]>(initialNodes);
  const edges = writable<Edge[]>(initialEdges);

  const router = createAvoidNodesRouter({
    onCollisionsResolved: (resolvedNodes) => {
      nodes.set(resolvedNodes as Node[]);
    },
  });

  $: router.reset($nodes as any, $edges as any);

  function handleNodeDrag(event: CustomEvent) {
    router.updateNodes($nodes as any);
  }

  function handleNodeDragStop(event: CustomEvent) {
    const resolved = resolveCollisions($nodes as any, { margin: 20, maxIterations: 50 });
    nodes.set(resolved as any);
    router.reset(resolved as any, $edges as any);
  }

  import { onDestroy } from "svelte";
  onDestroy(() => {
    router.destroy();
  });
</script>

<div class="flow-container">
  <SvelteFlow
    {nodes}
    {edges}
    {edgeTypes}
    fitView
    on:nodedrag={handleNodeDrag}
    on:nodedragstop={handleNodeDragStop}
  >
    <Background />
    <Controls />
    <MiniMap />
  </SvelteFlow>
</div>

<style>
  :global(body) {
    margin: 0;
    padding: 0;
    font-family:
      -apple-system,
      BlinkMacSystemFont,
      "Segoe UI",
      Roboto,
      sans-serif;
  }

  .flow-container {
    width: 100vw;
    height: 100vh;
  }
</style>
