// examples-svelte/demo/src/flows/AutoLayoutGroupsFlow.svelte
<script lang="ts">
  import { writable } from "svelte/store";
  import { onMount, onDestroy } from "svelte";
  import {
    SvelteFlow,
    SmoothStepEdge,
    StraightEdge,
    BezierEdge,
    Background,
    Controls,
    MiniMap,
    type Node,
    type Edge,
    type EdgeTypes,
  } from "@xyflow/svelte";
  import "@xyflow/svelte/dist/style.css";

  import AvoidNodesEdge from "avoid-nodes-edge-svelte/edge";
  import { createAvoidNodesRouter } from "avoid-nodes-edge-svelte";
  import { resolveCollisions } from "../utils/resolve-collisions";
  import { autoLayoutGroupNodes, autoLayoutGroupEdges } from "../initialElementsAutoLayoutGroups";
  import { runAutoLayoutWithGroups, type LayoutDirection, type LayoutAlgorithmName } from "../utils/auto-layout";
  import SettingsPanel from "../SettingsPanel.svelte";
  import FitViewOnLayout from "../FitViewOnLayout.svelte";
  import CurvedAvoidEdge from "../CurvedAvoidEdge.svelte";

  type EdgeStyle = "avoidNodes" | "curvedAvoid" | "default" | "smoothstep" | "straight";

  const edgeTypeMap: Record<EdgeStyle, EdgeTypes> = {
    avoidNodes: { avoidNodes: AvoidNodesEdge as any },
    curvedAvoid: { curvedAvoid: CurvedAvoidEdge as any },
    default: { default: BezierEdge as any },
    smoothstep: { smoothstep: SmoothStepEdge as any },
    straight: { straight: StraightEdge as any },
  };

  const edgeStyleLabels: { value: EdgeStyle; label: string }[] = [
    { value: "avoidNodes", label: "Avoid Nodes" },
    { value: "curvedAvoid", label: "Curved Avoid" },
    { value: "default", label: "Bezier" },
    { value: "smoothstep", label: "Smooth Step" },
    { value: "straight", label: "Straight" },
  ];

  let edgeStyle: EdgeStyle = "avoidNodes";
  let prevRounding = 8;

  $: edgeTypes = edgeTypeMap[edgeStyle] ?? {};

  function applyEdgeType(edgeList: Edge[], style: EdgeStyle): Edge[] {
    const type = style === "default" ? undefined : style;
    return edgeList.map((e) => ({ ...e, type }));
  }

  const nodes = writable<Node[]>(autoLayoutGroupNodes);
  const baseEdges = writable<Edge[]>(autoLayoutGroupEdges);

  const styledEdges = writable<Edge[]>(applyEdgeType(autoLayoutGroupEdges, edgeStyle));
  $: styledEdges.set(applyEdgeType($baseEdges, edgeStyle) as Edge[]);
  $: routerEdges = edgeStyle === "curvedAvoid"
    ? applyEdgeType($baseEdges, "avoidNodes")
    : $styledEdges;

  let settings = {
    edgeRounding: 8,
    edgeToEdgeSpacing: 10,
    edgeToNodeSpacing: 12,
    diagramGridSize: 0,
    shouldSplitEdgesNearHandle: true,
    autoBestSideConnection: true,
    resolveCollisions: true,
    connectorType: "orthogonal" as "orthogonal" | "bezier" | "polyline",
    layoutDirection: "LR" as LayoutDirection,
    layoutAlgorithm: "elk" as LayoutAlgorithmName,
    layoutSpacing: 60,
  };

  const router = createAvoidNodesRouter({
    onCollisionsResolved: (resolved) => nodes.set(resolved as Node[]),
  });

  $: routerOptions = {
    shapeBufferDistance: settings.edgeToNodeSpacing,
    idealNudgingDistance: settings.edgeToEdgeSpacing,
    edgeRounding: settings.edgeRounding,
    diagramGridSize: settings.diagramGridSize,
    shouldSplitEdgesNearHandle: settings.shouldSplitEdgesNearHandle,
    autoBestSideConnection: settings.autoBestSideConnection,
    connectorType: settings.connectorType,
  };

  $: router.reset($nodes, routerEdges, routerOptions);

  let didLayout = false;
  let fitViewTrigger = 0;

  async function applyLayout(currentNodes: Node[]) {
    const laid = await runAutoLayoutWithGroups(currentNodes, $baseEdges, {
      direction: settings.layoutDirection,
      algorithm: settings.layoutAlgorithm,
      spacing: settings.layoutSpacing,
    });
    nodes.set(laid);
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        router.reset(laid, routerEdges, routerOptions);
        fitViewTrigger++;
      });
    });
  }

  onMount(() => {
    setTimeout(() => {
      didLayout = true;
      applyLayout($nodes);
    }, 100);
  });

  let prevLayoutKey = `${settings.layoutDirection}-${settings.layoutAlgorithm}-${settings.layoutSpacing}`;
  $: {
    const key = `${settings.layoutDirection}-${settings.layoutAlgorithm}-${settings.layoutSpacing}`;
    if (didLayout && key !== prevLayoutKey) {
      prevLayoutKey = key;
      applyLayout($nodes);
    }
  }

  function handleNodeDrag() {
    router.updateNodes($nodes);
  }

  function handleNodeDragStop() {
    const current = settings.resolveCollisions
      ? resolveCollisions($nodes, { margin: 20, maxIterations: 50 })
      : $nodes;
    if (settings.resolveCollisions) nodes.set(current);
    router.reset(current, routerEdges, routerOptions);
  }

  function onSettingChange(e: CustomEvent<{ key: string; value: number | boolean }>) {
    settings = { ...settings, [e.detail.key]: e.detail.value };
  }

  function onLayoutChange(e: CustomEvent<{ key: string; value: string | number }>) {
    settings = { ...settings, [e.detail.key]: e.detail.value };
  }

  function onReLayout() {
    applyLayout($nodes);
  }

  function setEdgeStyle(value: EdgeStyle) {
    if (value === "curvedAvoid" && edgeStyle !== "curvedAvoid") {
      prevRounding = settings.edgeRounding;
      settings = {
        ...settings,
        edgeRounding: 0,
        edgeToEdgeSpacing: 16,
        edgeToNodeSpacing: 20,
        connectorType: "polyline",
        layoutAlgorithm: "elk" as LayoutAlgorithmName,
        layoutDirection: "LR" as LayoutDirection,
      };
    } else if (value !== "curvedAvoid" && edgeStyle === "curvedAvoid") {
      settings = {
        ...settings,
        edgeRounding: prevRounding,
        edgeToEdgeSpacing: 10,
        edgeToNodeSpacing: 12,
        connectorType: "orthogonal",
      };
    }
    edgeStyle = value;
    styledEdges.set(applyEdgeType($baseEdges, value));
    if (value === "avoidNodes" || value === "curvedAvoid") {
      requestAnimationFrame(() => router.reset($nodes, routerEdges, routerOptions));
    }
  }

  onDestroy(() => router.destroy());
</script>

<SvelteFlow
  {nodes}
  edges={styledEdges}
  {edgeTypes}
  fitView
  on:nodedrag={handleNodeDrag}
  on:nodedragstop={handleNodeDragStop}
>
  <FitViewOnLayout trigger={fitViewTrigger} />
  <Background />
  <Controls />
  <MiniMap />

  <!-- Edge style picker -->
  <div class="edge-picker">
    {#each edgeStyleLabels as { value, label }}
      <button
        class="edge-btn"
        class:active={edgeStyle === value}
        on:click={() => setEdgeStyle(value)}
      >
        {label}
      </button>
    {/each}
  </div>

  <SettingsPanel
    {...settings}
    showLayout={true}
    on:change={onSettingChange}
    on:layoutChange={onLayoutChange}
    on:reLayout={onReLayout}
  />
</SvelteFlow>

<style>
  .edge-picker {
    position: absolute;
    bottom: 24px;
    left: 12px;
    right: 12px;
    display: flex;
    justify-content: center;
    gap: 4px;
    z-index: 10;
    background: rgba(255, 255, 255, 0.95);
    border-radius: 8px;
    padding: 6px 10px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.12);
    overflow-x: auto;
  }

  .edge-btn {
    padding: 5px 12px;
    border-radius: 5px;
    border: 1px solid #ccc;
    background: #fff;
    color: #333;
    cursor: pointer;
    font-size: 12px;
    font-weight: 400;
    white-space: nowrap;
    flex-shrink: 0;
  }

  .edge-btn.active {
    background: #333;
    color: #fff;
    font-weight: 600;
  }
</style>

// examples-next/demo/src/flows/AutoLayoutGroupsFlow.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ReactFlow,
  addEdge,
  applyNodeChanges,
  applyEdgeChanges,
  Background,
  Controls,
  MiniMap,
  SmoothStepEdge,
  StraightEdge,
  type Node,
  type Edge,
  type NodeChange,
  type EdgeChange,
  type Connection,
  ProOptions,
  useReactFlow,
} from "@xyflow/react";

import { useAvoidNodesRouterFromWorker } from "avoid-nodes-edge";
import { AvoidNodesEdge } from "avoid-nodes-edge/edge";
import { CurvedAvoidEdge } from "../CurvedAvoidEdge";
import { resolveCollisions } from "../utils/resolve-collisions";
import { AutoLayoutSettingsPanel, type AutoLayoutSettings } from "../SettingsPanel";
import GroupNode from "../GroupNode";
import SelectedNodesToolbar from "../SelectedNodesToolbar";
import { autoLayoutGroupNodes, autoLayoutGroupEdges } from "../initialElementsAutoLayoutGroups";
import { runAutoLayoutWithGroups } from "../utils/auto-layout";

type EdgeStyle = "avoidNodes" | "curvedAvoid" | "default" | "smoothstep" | "straight";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const edgeTypeMap: Record<EdgeStyle, any> = {
  avoidNodes: { avoidNodes: AvoidNodesEdge },
  curvedAvoid: { curvedAvoid: CurvedAvoidEdge },
  default: {},
  smoothstep: { smoothstep: SmoothStepEdge },
  straight: { straight: StraightEdge },
};

const nodeTypes = { group: GroupNode };
const proOptions: ProOptions = { hideAttribution: true };

const edgeStyleLabels: { value: EdgeStyle; label: string }[] = [
  { value: "avoidNodes", label: "Avoid Nodes" },
  { value: "curvedAvoid", label: "Curved Avoid" },
  { value: "default", label: "Bezier" },
  { value: "smoothstep", label: "Smooth Step" },
  { value: "straight", label: "Straight" },
];

function applyEdgeType(edges: Edge[], edgeStyle: EdgeStyle): Edge[] {
  const type = edgeStyle === "default" ? undefined : edgeStyle;
  return edges.map((e) => ({ ...e, type }));
}

export default function AutoLayoutGroupsFlow() {
  const [nodes, setNodes] = useState<Node[]>(autoLayoutGroupNodes);
  const [edges, setEdges] = useState<Edge[]>(autoLayoutGroupEdges);
  const [edgeStyle, setEdgeStyle] = useState<EdgeStyle>("avoidNodes");
  const prevRoundingRef = useRef(8);
  const [settings, setSettings] = useState<AutoLayoutSettings>({
    edgeRounding: 8,
    edgeToEdgeSpacing: 10,
    edgeToNodeSpacing: 12,
    diagramGridSize: 0,
    shouldSplitEdgesNearHandle: true,
    autoBestSideConnection: true,
    resolveCollisions: true,
    layoutDirection: "LR",
    layoutAlgorithm: "elk",
    layoutSpacing: 60,
    connectorType: "orthogonal",
  });

  const styledEdges = useMemo(() => applyEdgeType(edges, edgeStyle), [edges, edgeStyle]);
  const routerEdges = useMemo(
    () => edgeStyle === "curvedAvoid" ? applyEdgeType(edges, "avoidNodes") : styledEdges,
    [edges, edgeStyle, styledEdges]
  );
  const edgeTypes = useMemo(() => edgeTypeMap[edgeStyle] ?? {}, [edgeStyle]);

  const { updateRoutingOnNodesChange, resetRouting } = useAvoidNodesRouterFromWorker(nodes, routerEdges, settings);
  const { fitView } = useReactFlow();
  const didLayout = useRef(false);

  const applyLayout = useCallback(
    async (currentNodes: Node[]) => {
      const laid = await runAutoLayoutWithGroups(currentNodes, edges, {
        direction: settings.layoutDirection,
        algorithm: settings.layoutAlgorithm,
        spacing: settings.layoutSpacing,
      });
      setNodes(laid);
      requestAnimationFrame(() => requestAnimationFrame(() => {
        resetRouting();
        fitView({ duration: 300 });
      }));
    },
    [edges, settings.layoutDirection, settings.layoutAlgorithm, settings.layoutSpacing, resetRouting, fitView]
  );

  useEffect(() => {
    if (!didLayout.current) {
      const timer = setTimeout(() => {
        didLayout.current = true;
        applyLayout(nodes);
      }, 100);
      return () => clearTimeout(timer);
    }
    applyLayout(nodes);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [settings.layoutDirection, settings.layoutAlgorithm, settings.layoutSpacing]);

  useEffect(() => {
    if (edgeStyle === "avoidNodes" || edgeStyle === "curvedAvoid") {
      requestAnimationFrame(() => resetRouting());
    }
  }, [edgeStyle, resetRouting]);

  const onNodesChange = useCallback(
    (changes: NodeChange<Node>[]) => {
      setNodes((nds) => applyNodeChanges(changes, nds));
      updateRoutingOnNodesChange(changes);
    },
    [updateRoutingOnNodesChange]
  );

  const deferredReset = useCallback(() => {
    requestAnimationFrame(() => resetRouting());
  }, [resetRouting]);

  const onEdgesChange = useCallback(
    (changes: EdgeChange<Edge>[]) => {
      setEdges((eds) => applyEdgeChanges(changes, eds));
      const needsReset = changes.some((c) => c.type === "add" || c.type === "remove");
      if (needsReset) deferredReset();
    },
    [deferredReset]
  );

  const onConnect = useCallback(
    (params: Connection) => {
      setEdges((eds) => addEdge({ ...params, type: edgeStyle === "default" ? undefined : edgeStyle }, eds));
      if (edgeStyle === "avoidNodes" || edgeStyle === "curvedAvoid") deferredReset();
    },
    [deferredReset, edgeStyle]
  );

  const onNodeDragStop = useCallback(
    (_event: React.MouseEvent, _node: Node) => {
      if (settings.resolveCollisions) {
        setNodes((nds) => resolveCollisions(nds, { margin: 20, maxIterations: 50 }));
      }
      deferredReset();
    },
    [deferredReset, settings.resolveCollisions]
  );

  const onSettingChange = useCallback(
    (key: string, value: number | boolean) => {
      setSettings((prev) => ({ ...prev, [key]: value }));
    },
    []
  );

  const onLayoutChange = useCallback(
    (key: string, value: string | number) => {
      setSettings((prev) => ({ ...prev, [key]: value }));
    },
    []
  );

  const onReLayout = useCallback(() => {
    applyLayout(nodes);
  }, [applyLayout, nodes]);

  return (
    <ReactFlow
      nodes={nodes}
      edges={styledEdges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onConnect={onConnect}
      onNodeDragStop={onNodeDragStop}
      nodeTypes={nodeTypes}
      edgeTypes={edgeTypes}
      defaultEdgeOptions={{ type: edgeStyle === "default" ? undefined : edgeStyle }}
      fitView
      minZoom={0.01}
      maxZoom={100}
      proOptions={proOptions}
      selectNodesOnDrag={false}
    >
      <Background />
      <Controls />
      <MiniMap />
      <SelectedNodesToolbar />
      {/* Edge style picker */}
      <div
        style={{
          position: "absolute",
          bottom: 24,
          left: 12,
          right: 12,
          display: "flex",
          justifyContent: "center",
          gap: 4,
          zIndex: 10,
          background: "rgba(255,255,255,0.95)",
          borderRadius: 8,
          padding: "6px 10px",
          boxShadow: "0 2px 8px rgba(0,0,0,0.12)",
          overflowX: "auto",
        }}
      >
        {edgeStyleLabels.map(({ value, label }) => (
          <button
            key={value}
            onClick={() => {
              setEdgeStyle((prev) => {
                if (value === "curvedAvoid" && prev !== "curvedAvoid") {
                  prevRoundingRef.current = settings.edgeRounding;
                  setSettings((s) => ({
                    ...s,
                    edgeRounding: 0,
                    edgeToEdgeSpacing: 16,
                    edgeToNodeSpacing: 20,
                    connectorType: "polyline",
                  }));
                } else if (value !== "curvedAvoid" && prev === "curvedAvoid") {
                  setSettings((s) => ({
                    ...s,
                    edgeRounding: prevRoundingRef.current,
                    edgeToEdgeSpacing: 10,
                    edgeToNodeSpacing: 12,
                    connectorType: "orthogonal",
                  }));
                }
                return value;
              });
            }}
            style={{
              padding: "5px 12px",
              borderRadius: 5,
              border: "1px solid #ccc",
              background: edgeStyle === value ? "#333" : "#fff",
              color: edgeStyle === value ? "#fff" : "#333",
              cursor: "pointer",
              fontSize: 12,
              fontWeight: edgeStyle === value ? 600 : 400,
              whiteSpace: "nowrap",
            }}
          >
            {label}
          </button>
        ))}
      </div>
      <AutoLayoutSettingsPanel
        settings={settings}
        onChange={onSettingChange}
        onLayoutChange={onLayoutChange}
        onReLayout={onReLayout}
      />
    </ReactFlow>
  );
}
