// examples-next/demo/src/SettingsPanel.tsx
import { useState } from "react";
import type { LayoutDirection, LayoutAlgorithmName } from "./utils/auto-layout";

type ConnectorType = "orthogonal" | "bezier" | "polyline" | "step" | "linear" | "catmull-rom" | "bezier-catmull-rom";

const isMobile = () => typeof window !== "undefined" && window.innerWidth < 768;

const getPanelStyle = (): React.CSSProperties => ({
  position: "absolute",
  top: 52,
  right: 12,
  background: "rgba(255, 255, 255, 0.95)",
  borderRadius: 8,
  padding: 16,
  boxShadow: "0 2px 8px rgba(0,0,0,0.15)",
  zIndex: 10,
  minWidth: 240,
  maxWidth: "min(320px, calc(100vw - 24px))",
  maxHeight: "calc(100vh - 64px)",
  overflowY: "auto",
  fontSize: 13,
});

const rowStyle: React.CSSProperties = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  marginBottom: 10,
};

export type Settings = {
  edgeRounding: number;
  edgeToEdgeSpacing: number;
  edgeToNodeSpacing: number;
  diagramGridSize: number;
  shouldSplitEdgesNearHandle: boolean;
  autoBestSideConnection: boolean;
  resolveCollisions: boolean;
  connectorType: ConnectorType;
};

export type AutoLayoutSettings = Settings & {
  layoutDirection: LayoutDirection;
  layoutAlgorithm: LayoutAlgorithmName;
  layoutSpacing: number;
  connectorType: ConnectorType;
};

function BooleanToggle({
  label,
  value,
  onChange,
}: {
  label: string;
  value: boolean;
  onChange: (val: boolean) => void;
}) {
  return (
    <div style={rowStyle}>
      <label>{label}</label>
      <div style={{ display: "flex", gap: 4 }}>
        {[true, false].map((val) => (
          <button
            key={String(val)}
            onClick={() => onChange(val)}
            style={{
              padding: "4px 10px",
              borderRadius: 4,
              border: "1px solid #ccc",
              background: value === val ? "#333" : "#fff",
              color: value === val ? "#fff" : "#333",
              cursor: "pointer",
            }}
          >
            {val ? "True" : "False"}
          </button>
        ))}
      </div>
    </div>
  );
}

export function SettingsPanel({
  settings,
  onChange,
}: {
  settings: Settings;
  onChange: (key: string, value: number | boolean | string) => void;
}) {
  const [open, setOpen] = useState(() => !isMobile());
  const sliders = [
    { key: "edgeRounding", label: "Edge Rounding", min: 0, max: 200 },
    { key: "edgeToEdgeSpacing", label: "Edge-to-Edge Spacing", min: 0, max: 24 },
    { key: "edgeToNodeSpacing", label: "Edge-to-Node Spacing", min: 0, max: 48 },
    { key: "diagramGridSize", label: "Diagram Grid Size", min: 0, max: 48 },
  ] as const;

  return (
    <div style={getPanelStyle()}>
      <div
        style={{ fontWeight: 600, marginBottom: open ? 12 : 0, cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", userSelect: "none" }}
        onClick={() => setOpen(!open)}
      >
        <span>{open ? "Settings" : "\u2699\uFE0F Settings"}</span>
        <span style={{ fontSize: 11, color: "#888" }}>{open ? "\u2715" : ""}</span>
      </div>
      {open && (
        <>
          <div style={rowStyle}>
            <label>Connector Type</label>
            <select
              value={settings.connectorType}
              onChange={(e) => onChange("connectorType", e.target.value)}
              style={{ padding: "4px 8px", borderRadius: 4, border: "1px solid #ccc" }}
            >
              <option value="orthogonal">Orthogonal</option>
              <option value="bezier">Bezier</option>
              <option value="polyline">Polyline</option>
              <option value="step">Step</option>
              <option value="linear">Linear</option>
              <option value="catmull-rom">Catmull-Rom</option>
              <option value="bezier-catmull-rom">Bezier Catmull-Rom</option>
            </select>
          </div>
          {sliders.map(({ key, label, min, max }) => (
            <div key={key} style={rowStyle}>
              <label>{label}</label>
              <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                <input
                  type="range"
                  min={min}
                  max={max}
                  value={settings[key]}
                  onChange={(e) => onChange(key, Number(e.target.value))}
                  style={{ width: 100 }}
                />
                <input
                  type="number"
                  min={0}
                  value={settings[key]}
                  onChange={(e) => onChange(key, Math.max(0, Number(e.target.value)))}
                  style={{ width: 48, textAlign: "right", padding: "2px 4px", borderRadius: 4, border: "1px solid #ccc", fontSize: 12 }}
                />
              </div>
            </div>
          ))}
          <BooleanToggle label="Split Edges Near Handle" value={settings.shouldSplitEdgesNearHandle} onChange={(val) => onChange("shouldSplitEdgesNearHandle", val)} />
          <BooleanToggle label="Resolve Collisions" value={settings.resolveCollisions} onChange={(val) => onChange("resolveCollisions", val)} />
          <BooleanToggle label="Auto Best Side" value={settings.autoBestSideConnection} onChange={(val) => onChange("autoBestSideConnection", val)} />
        </>
      )}
    </div>
  );
}

export function AutoLayoutSettingsPanel({
  settings,
  onChange,
  onLayoutChange,
  onReLayout,
}: {
  settings: AutoLayoutSettings;
  onChange: (key: string, value: number | boolean) => void;
  onLayoutChange: (key: string, value: string | number) => void;
  onReLayout: () => void;
}) {
  const sliders = [
    { key: "edgeRounding", label: "Edge Rounding", min: 0, max: 200 },
    { key: "edgeToEdgeSpacing", label: "Edge-to-Edge Spacing", min: 0, max: 24 },
    { key: "edgeToNodeSpacing", label: "Edge-to-Node Spacing", min: 0, max: 48 },
  ] as const;

  const [open, setOpen] = useState(() => !isMobile());

  return (
    <div style={getPanelStyle()}>
      <div
        style={{ fontWeight: 600, marginBottom: open ? 12 : 0, cursor: "pointer", display: "flex", justifyContent: "space-between", alignItems: "center", userSelect: "none" }}
        onClick={() => setOpen(!open)}
      >
        <span>{open ? "Auto Layout + libavoid" : "\u2699\uFE0F Auto Layout"}</span>
        <span style={{ fontSize: 11, color: "#888" }}>{open ? "\u2715" : ""}</span>
      </div>
      {!open ? null : (
      <>
      <div style={{ fontWeight: 500, marginBottom: 8, fontSize: 12, color: "#888" }}>Layout Engine</div>
      <div style={rowStyle}>
        <label>Algorithm</label>
        <select
          value={settings.layoutAlgorithm}
          onChange={(e) => onLayoutChange("layoutAlgorithm", e.target.value)}
          style={{ padding: "4px 8px", borderRadius: 4, border: "1px solid #ccc" }}
        >
          <option value="elk">ELK (Layered)</option>
          <option value="dagre">Dagre</option>
          <option value="d3-hierarchy">D3 Hierarchy</option>
        </select>
      </div>
      <div style={rowStyle}>
        <label>Direction</label>
        <select
          value={settings.layoutDirection}
          onChange={(e) => onLayoutChange("layoutDirection", e.target.value)}
          style={{ padding: "4px 8px", borderRadius: 4, border: "1px solid #ccc" }}
        >
          <option value="LR">Left to Right</option>
          <option value="TB">Top to Bottom</option>
          <option value="RL">Right to Left</option>
          <option value="BT">Bottom to Top</option>
        </select>
      </div>
      <div style={rowStyle}>
        <label>Node Spacing</label>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
          <input
            type="range"
            min={20}
            max={120}
            value={settings.layoutSpacing}
            onChange={(e) => onLayoutChange("layoutSpacing", Number(e.target.value))}
            style={{ width: 100 }}
          />
          <input
            type="number"
            min={0}
            value={settings.layoutSpacing}
            onChange={(e) => onLayoutChange("layoutSpacing", Math.max(0, Number(e.target.value)))}
            style={{ width: 48, textAlign: "right", padding: "2px 4px", borderRadius: 4, border: "1px solid #ccc", fontSize: 12 }}
          />
        </div>
      </div>
      <div style={{ marginBottom: 12 }}>
        <button
          onClick={onReLayout}
          style={{
            padding: "6px 16px",
            borderRadius: 6,
            border: "1px solid #818cf8",
            background: "#818cf8",
            color: "#fff",
            cursor: "pointer",
            fontSize: 13,
            fontWeight: 600,
            width: "100%",
          }}
        >
          Re-Layout
        </button>
      </div>

      <div style={{ fontWeight: 500, marginBottom: 8, fontSize: 12, color: "#888" }}>libavoid Routing</div>
      <div style={rowStyle}>
        <label>Connector Type</label>
        <select
          value={settings.connectorType}
          onChange={(e) => onLayoutChange("connectorType", e.target.value)}
          style={{ padding: "4px 8px", borderRadius: 4, border: "1px solid #ccc" }}
        >
          <option value="orthogonal">Orthogonal</option>
          <option value="bezier">Bezier</option>
          <option value="polyline">Polyline</option>
          <option value="step">Step</option>
          <option value="linear">Linear</option>
          <option value="catmull-rom">Catmull-Rom</option>
          <option value="bezier-catmull-rom">Bezier Catmull-Rom</option>
        </select>
      </div>
      {sliders.map(({ key, label, min, max }) => (
        <div key={key} style={rowStyle}>
          <label>{label}</label>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <input
              type="range"
              min={min}
              max={max}
              value={settings[key]}
              onChange={(e) => onChange(key, Number(e.target.value))}
              style={{ width: 100 }}
            />
            <input
              type="number"
              min={0}
              value={settings[key]}
              onChange={(e) => onChange(key, Math.max(0, Number(e.target.value)))}
              style={{ width: 48, textAlign: "right", padding: "2px 4px", borderRadius: 4, border: "1px solid #ccc", fontSize: 12 }}
            />
          </div>
        </div>
      ))}
      <BooleanToggle label="Auto Best Side" value={settings.autoBestSideConnection} onChange={(val) => onChange("autoBestSideConnection", val)} />
      <BooleanToggle label="Resolve Collisions" value={settings.resolveCollisions} onChange={(val) => onChange("resolveCollisions", val)} />
      </>
      )}
    </div>
  );
}

// examples-svelte/demo/src/SettingsPanel.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";

  export let edgeRounding = 8;
  export let edgeToEdgeSpacing = 10;
  export let edgeToNodeSpacing = 12;
  export let diagramGridSize = 0;
  export let shouldSplitEdgesNearHandle = true;
  export let autoBestSideConnection = true;
  export let resolveCollisions = true;
  export let connectorType: "orthogonal" | "bezier" | "polyline" = "orthogonal";

  export let showLayout = false;
  export let layoutAlgorithm = "elk";
  export let layoutDirection = "LR";
  export let layoutSpacing = 60;

  const dispatch = createEventDispatcher();

  const mobile = typeof window !== "undefined" && window.innerWidth < 768;
  let open = !mobile;

  function onSlider(key: string, e: Event) {
    const val = Number((e.target as HTMLInputElement).value);
    dispatch("change", { key, value: val });
  }

  function onToggle(key: string, val: boolean) {
    dispatch("change", { key, value: val });
  }

  function onLayoutChange(key: string, value: string | number) {
    dispatch("layoutChange", { key, value });
  }

  function onReLayout() {
    dispatch("reLayout");
  }

  const sliders = [
    { key: "edgeRounding", label: "Edge Rounding", min: 0, max: 200 },
    { key: "edgeToEdgeSpacing", label: "Edge-to-Edge Spacing", min: 0, max: 24 },
    { key: "edgeToNodeSpacing", label: "Edge-to-Node Spacing", min: 0, max: 48 },
    { key: "diagramGridSize", label: "Diagram Grid Size", min: 0, max: 48 },
  ] as const;

  const layoutSliders = [
    { key: "edgeRounding", label: "Edge Rounding", min: 0, max: 200 },
    { key: "edgeToEdgeSpacing", label: "Edge-to-Edge Spacing", min: 0, max: 24 },
    { key: "edgeToNodeSpacing", label: "Edge-to-Node Spacing", min: 0, max: 48 },
  ] as const;

  $: values = {
    edgeRounding,
    edgeToEdgeSpacing,
    edgeToNodeSpacing,
    diagramGridSize,
  } as Record<string, number>;
</script>

<div class="panel">
  <div class="header" on:click={() => (open = !open)}>
    <span>{open ? (showLayout ? "Auto Layout + libavoid" : "Settings") : (showLayout ? "\u2699\uFE0F Auto Layout" : "\u2699\uFE0F Settings")}</span>
    <span class="toggle">{open ? "\u2715" : ""}</span>
  </div>

  {#if open}
    {#if showLayout}
      <div class="section-label">Layout Engine</div>

      <div class="row">
        <label>Algorithm</label>
        <select value={layoutAlgorithm} on:change={(e) => onLayoutChange("layoutAlgorithm", e.currentTarget.value)}>
          <option value="elk">ELK (Layered)</option>
          <option value="dagre">Dagre</option>
          <option value="d3-hierarchy">D3 Hierarchy</option>
        </select>
      </div>

      <div class="row">
        <label>Direction</label>
        <select value={layoutDirection} on:change={(e) => onLayoutChange("layoutDirection", e.currentTarget.value)}>
          <option value="LR">Left to Right</option>
          <option value="TB">Top to Bottom</option>
          <option value="RL">Right to Left</option>
          <option value="BT">Bottom to Top</option>
        </select>
      </div>

      <div class="row">
        <label>Node Spacing</label>
        <div class="slider-group">
          <input type="range" min={20} max={120} value={layoutSpacing} on:input={(e) => onLayoutChange("layoutSpacing", Number(e.currentTarget.value))} />
          <input type="number" class="num-input" min={0} value={layoutSpacing} on:input={(e) => onLayoutChange("layoutSpacing", Math.max(0, Number(e.currentTarget.value)))} />
        </div>
      </div>

      <button class="relayout-btn" on:click={onReLayout}>Re-Layout</button>

      <div class="section-label">libavoid Routing</div>

      <div class="row">
        <label>Connector Type</label>
        <select value={connectorType} on:change={(e) => onLayoutChange("connectorType", e.currentTarget.value)}>
          <option value="orthogonal">Orthogonal</option>
          <option value="bezier">Bezier</option>
          <option value="polyline">Polyline</option>
          <option value="step">Step</option>
          <option value="linear">Linear</option>
          <option value="catmull-rom">Catmull-Rom</option>
          <option value="bezier-catmull-rom">Bezier Catmull-Rom</option>
        </select>
      </div>

      {#each layoutSliders as { key, label, min, max }}
        <div class="row">
          <label>{label}</label>
          <div class="slider-group">
            <input type="range" {min} {max} value={values[key]} on:input={(e) => onSlider(key, e)} />
            <input type="number" class="num-input" min={0} value={values[key]} on:input={(e) => onSlider(key, e)} />
          </div>
        </div>
      {/each}

      <div class="row">
        <label>Auto Best Side</label>
        <div class="btn-group">
          <button class:active={autoBestSideConnection} on:click={() => onToggle("autoBestSideConnection", true)}>True</button>
          <button class:active={!autoBestSideConnection} on:click={() => onToggle("autoBestSideConnection", false)}>False</button>
        </div>
      </div>

      <div class="row">
        <label>Resolve Collisions</label>
        <div class="btn-group">
          <button class:active={resolveCollisions} on:click={() => onToggle("resolveCollisions", true)}>True</button>
          <button class:active={!resolveCollisions} on:click={() => onToggle("resolveCollisions", false)}>False</button>
        </div>
      </div>
    {:else}
      <div class="row">
        <label>Connector Type</label>
        <select value={connectorType} on:change={(e) => { dispatch("change", { key: "connectorType", value: e.currentTarget.value }); }}>
          <option value="orthogonal">Orthogonal</option>
          <option value="bezier">Bezier</option>
          <option value="polyline">Polyline</option>
          <option value="step">Step</option>
          <option value="linear">Linear</option>
          <option value="catmull-rom">Catmull-Rom</option>
          <option value="bezier-catmull-rom">Bezier Catmull-Rom</option>
        </select>
      </div>

      {#each sliders as { key, label, min, max }}
        <div class="row">
          <label>{label}</label>
          <div class="slider-group">
            <input type="range" {min} {max} value={values[key]} on:input={(e) => onSlider(key, e)} />
            <input type="number" class="num-input" min={0} value={values[key]} on:input={(e) => onSlider(key, e)} />
          </div>
        </div>
      {/each}

      <div class="row">
        <label>Split Edges Near Handle</label>
        <div class="btn-group">
          <button class:active={shouldSplitEdgesNearHandle} on:click={() => onToggle("shouldSplitEdgesNearHandle", true)}>True</button>
          <button class:active={!shouldSplitEdgesNearHandle} on:click={() => onToggle("shouldSplitEdgesNearHandle", false)}>False</button>
        </div>
      </div>

      <div class="row">
        <label>Resolve Collisions</label>
        <div class="btn-group">
          <button class:active={resolveCollisions} on:click={() => onToggle("resolveCollisions", true)}>True</button>
          <button class:active={!resolveCollisions} on:click={() => onToggle("resolveCollisions", false)}>False</button>
        </div>
      </div>

      <div class="row">
        <label>Auto Best Side</label>
        <div class="btn-group">
          <button class:active={autoBestSideConnection} on:click={() => onToggle("autoBestSideConnection", true)}>True</button>
          <button class:active={!autoBestSideConnection} on:click={() => onToggle("autoBestSideConnection", false)}>False</button>
        </div>
      </div>
    {/if}
  {/if}
</div>

<style>
  .panel {
    position: absolute;
    top: 52px;
    right: 12px;
    background: rgba(255, 255, 255, 0.95);
    border-radius: 8px;
    padding: 16px;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
    z-index: 10;
    min-width: 240px;
    max-width: min(320px, calc(100vw - 24px));
    max-height: calc(100vh - 64px);
    overflow-y: auto;
    font-size: 13px;
  }

  .header {
    font-weight: 600;
    cursor: pointer;
    display: flex;
    justify-content: space-between;
    align-items: center;
    user-select: none;
  }

  .toggle {
    font-size: 11px;
    color: #888;
  }

  .section-label {
    font-weight: 500;
    margin-bottom: 8px;
    margin-top: 8px;
    font-size: 12px;
    color: #888;
  }

  .row {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 10px;
  }

  .slider-group {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .slider-group input[type="range"] {
    width: 100px;
  }

  .num-input {
    width: 48px;
    text-align: right;
    padding: 2px 4px;
    border-radius: 4px;
    border: 1px solid #ccc;
    font-size: 12px;
  }

  .btn-group {
    display: flex;
    gap: 4px;
  }

  .btn-group button {
    padding: 4px 10px;
    border-radius: 4px;
    border: 1px solid #ccc;
    background: #fff;
    color: #333;
    cursor: pointer;
  }

  .btn-group button.active {
    background: #333;
    color: #fff;
  }

  select {
    padding: 4px 8px;
    border-radius: 4px;
    border: 1px solid #ccc;
  }

  .relayout-btn {
    padding: 6px 16px;
    border-radius: 6px;
    border: 1px solid #818cf8;
    background: #818cf8;
    color: #fff;
    cursor: pointer;
    font-size: 13px;
    font-weight: 600;
    width: 100%;
    margin-bottom: 12px;
  }
</style>
