// examples-svelte/demo/src/flows/AutoLayoutFlow.svelte
<script lang="ts">
  import { writable } from "svelte/store";
  import { onMount, onDestroy } from "svelte";
  import {
    SvelteFlow,
    Background,
    Controls,
    MiniMap,
    type Node,
    type Edge,
    type EdgeTypes,
  } from "@xyflow/svelte";
  import "@xyflow/svelte/dist/style.css";

  import AvoidNodesEdge from "avoid-nodes-edge-svelte/edge";
  import { createAvoidNodesRouter } from "avoid-nodes-edge-svelte";
  import { resolveCollisions } from "../utils/resolve-collisions";
  import { elkNodes, elkEdges } from "../initialElementsElk";
  import { runAutoLayout, type LayoutDirection, type LayoutAlgorithmName } from "../utils/auto-layout";
  import SettingsPanel from "../SettingsPanel.svelte";

  const edgeTypes: EdgeTypes = { avoidNodes: AvoidNodesEdge as any };

  const nodes = writable<Node[]>(elkNodes);
  const edges = writable<Edge[]>(elkEdges);

  let settings = {
    edgeRounding: 8,
    edgeToEdgeSpacing: 10,
    edgeToNodeSpacing: 12,
    diagramGridSize: 0,
    shouldSplitEdgesNearHandle: true,
    autoBestSideConnection: true,
    resolveCollisions: true,
    layoutDirection: "LR" as LayoutDirection,
    layoutAlgorithm: "elk" as LayoutAlgorithmName,
    layoutSpacing: 60,
  };

  const router = createAvoidNodesRouter({
    onCollisionsResolved: (resolved) => nodes.set(resolved as Node[]),
  });

  $: routerOptions = {
    shapeBufferDistance: settings.edgeToNodeSpacing,
    idealNudgingDistance: settings.edgeToEdgeSpacing,
    edgeRounding: settings.edgeRounding,
    diagramGridSize: settings.diagramGridSize,
    shouldSplitEdgesNearHandle: settings.shouldSplitEdgesNearHandle,
    autoBestSideConnection: settings.autoBestSideConnection,
  };

  $: router.reset($nodes, $edges, routerOptions);

  let didLayout = false;

  async function applyLayout(currentNodes: Node[]) {
    const laid = await runAutoLayout(currentNodes, $edges, {
      direction: settings.layoutDirection,
      algorithm: settings.layoutAlgorithm,
      spacing: settings.layoutSpacing,
    });
    nodes.set(laid);
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        router.reset(laid, $edges, routerOptions);
      });
    });
  }

  onMount(() => {
    setTimeout(() => {
      didLayout = true;
      applyLayout($nodes);
    }, 100);
  });

  // Re-layout when layout settings change
  let prevLayoutKey = `${settings.layoutDirection}-${settings.layoutAlgorithm}-${settings.layoutSpacing}`;
  $: {
    const key = `${settings.layoutDirection}-${settings.layoutAlgorithm}-${settings.layoutSpacing}`;
    if (didLayout && key !== prevLayoutKey) {
      prevLayoutKey = key;
      applyLayout($nodes);
    }
  }

  function handleNodeDrag() {
    router.updateNodes($nodes);
  }

  function handleNodeDragStop() {
    if (settings.resolveCollisions) {
      const resolved = resolveCollisions($nodes, { margin: 20, maxIterations: 50 });
      nodes.set(resolved);
    }
    router.reset($nodes, $edges, routerOptions);
  }

  function onSettingChange(e: CustomEvent<{ key: string; value: number | boolean }>) {
    settings = { ...settings, [e.detail.key]: e.detail.value };
  }

  function onLayoutChange(e: CustomEvent<{ key: string; value: string | number }>) {
    settings = { ...settings, [e.detail.key]: e.detail.value };
  }

  function onReLayout() {
    applyLayout($nodes);
  }

  onDestroy(() => router.destroy());
</script>

<SvelteFlow
  {nodes}
  {edges}
  {edgeTypes}
  fitView
  on:nodedrag={handleNodeDrag}
  on:nodedragstop={handleNodeDragStop}
>
  <Background />
  <Controls />
  <MiniMap />
  <SettingsPanel
    {...settings}
    showLayout={true}
    on:change={onSettingChange}
    on:layoutChange={onLayoutChange}
    on:reLayout={onReLayout}
  />
</SvelteFlow>

// examples/demo/src/flows/AutoLayoutFlow.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import {
  ReactFlow,
  addEdge,
  applyNodeChanges,
  applyEdgeChanges,
  Background,
  Controls,
  MiniMap,
  type Node,
  type Edge,
  type NodeChange,
  type EdgeChange,
  type Connection,
  ProOptions,
  useReactFlow,
} from "@xyflow/react";

import { useAvoidNodesRouterFromWorker } from "avoid-nodes-edge";
import { AvoidNodesEdge } from "avoid-nodes-edge/edge";
import { resolveCollisions } from "../utils/resolve-collisions";
import { AutoLayoutSettingsPanel, type AutoLayoutSettings } from "../SettingsPanel";
import { elkNodes, elkEdges } from "../initialElementsElk";
import { runAutoLayout } from "../utils/auto-layout";

const edgeTypes = { avoidNodes: AvoidNodesEdge };
const proOptions: ProOptions = { hideAttribution: true };

export default function AutoLayoutFlow() {
  const [nodes, setNodes] = useState<Node[]>(elkNodes);
  const [edges, setEdges] = useState<Edge[]>(elkEdges);
  const [settings, setSettings] = useState<AutoLayoutSettings>({
    edgeRounding: 8,
    edgeToEdgeSpacing: 10,
    edgeToNodeSpacing: 12,
    diagramGridSize: 0,
    shouldSplitEdgesNearHandle: true,
    autoBestSideConnection: true,
    resolveCollisions: true,
    layoutDirection: "LR",
    layoutAlgorithm: "elk",
    layoutSpacing: 60,
  });

  const { updateRoutingOnNodesChange, resetRouting } = useAvoidNodesRouterFromWorker(nodes, edges, settings);
  const { fitView } = useReactFlow();
  const didLayout = useRef(false);

  const applyLayout = useCallback(
    async (currentNodes: Node[]) => {
      const laid = await runAutoLayout(currentNodes, edges, {
        direction: settings.layoutDirection,
        algorithm: settings.layoutAlgorithm,
        spacing: settings.layoutSpacing,
      });
      setNodes(laid);
      requestAnimationFrame(() => requestAnimationFrame(() => {
        resetRouting();
        fitView({ duration: 300 });
      }));
    },
    [edges, settings.layoutDirection, settings.layoutAlgorithm, settings.layoutSpacing, resetRouting, fitView]
  );

  useEffect(() => {
    if (!didLayout.current) {
      const timer = setTimeout(() => {
        didLayout.current = true;
        applyLayout(nodes);
      }, 100);
      return () => clearTimeout(timer);
    }
    applyLayout(nodes);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [settings.layoutDirection, settings.layoutAlgorithm, settings.layoutSpacing]);

  const onNodesChange = useCallback(
    (changes: NodeChange<Node>[]) => {
      setNodes((nds) => applyNodeChanges(changes, nds));
      updateRoutingOnNodesChange(changes);
    },
    [updateRoutingOnNodesChange]
  );

  const deferredReset = useCallback(() => {
    requestAnimationFrame(() => resetRouting());
  }, [resetRouting]);

  const onEdgesChange = useCallback(
    (changes: EdgeChange<Edge>[]) => {
      setEdges((eds) => applyEdgeChanges(changes, eds));
      const needsReset = changes.some((c) => c.type === "add" || c.type === "remove");
      if (needsReset) deferredReset();
    },
    [deferredReset]
  );

  const onConnect = useCallback(
    (params: Connection) => {
      setEdges((eds) => addEdge({ ...params, type: "avoidNodes" }, eds));
      deferredReset();
    },
    [deferredReset]
  );

  const onNodeDragStop = useCallback(
    (_event: React.MouseEvent, _node: Node) => {
      if (settings.resolveCollisions) {
        setNodes((nds) => resolveCollisions(nds, { margin: 20, maxIterations: 50 }));
      }
      deferredReset();
    },
    [deferredReset, settings.resolveCollisions]
  );

  const onSettingChange = useCallback(
    (key: string, value: number | boolean) => {
      setSettings((prev) => ({ ...prev, [key]: value }));
    },
    []
  );

  const onLayoutChange = useCallback(
    (key: string, value: string | number) => {
      setSettings((prev) => ({ ...prev, [key]: value }));
    },
    []
  );

  const onReLayout = useCallback(() => {
    applyLayout(nodes);
  }, [applyLayout, nodes]);

  return (
    <ReactFlow
      nodes={nodes}
      edges={edges}
      onNodesChange={onNodesChange}
      onEdgesChange={onEdgesChange}
      onConnect={onConnect}
      onNodeDragStop={onNodeDragStop}
      edgeTypes={edgeTypes}
      defaultEdgeOptions={{ type: "avoidNodes" }}
      fitView
      minZoom={0.01}
      maxZoom={100}
      proOptions={proOptions}
      selectNodesOnDrag={false}
    >
      <Background />
      <Controls />
      <MiniMap />
      <AutoLayoutSettingsPanel
        settings={settings}
        onChange={onSettingChange}
        onLayoutChange={onLayoutChange}
        onReLayout={onReLayout}
      />
    </ReactFlow>
  );
}
